//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Sovos Compliance Systems, Inc")]
[assembly: AssemblyDescription("Sovos Compliance Systems, Inc")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Sovos Compliance Systems, Inc")]
[assembly: AssemblyProduct("Sovos Compliance Systems, Inc")]
[assembly: AssemblyCopyright("Sovos Compliance Systems, Inc")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]


[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

 


